### ISSUE TITLE
Camera always in use

### ISSUE THREAD

**Issue by Marco97raf** [apizee/reactNativeApiRTC#7] opened 2020-05-21 16:20 UTC
Hi,
i'm working on a video call project with an android device, so I started with react-native (and react for web page).
I run into a problem with the release of camera. It stay busy also after an hungup.
I haven't found any solution in documentation.

I'm using the react native library of this project "apiRTC-React.min.js".
Anyone can help me?

Thank you.

**Comment by FredLuart** [comment] 2020-05-26 16:23
This is fixed on the last demo update. Can you test it ?

**Comment by Marco97raf** [comment] 2020-05-27 07:32
Yes, I import the new file apiRTC-React.min.js, but when the app starts this error occurs: "document.addEventListener is not a function" on line 3:526341 of the minified file.

**Comment by FredLuart** [comment] 2020-05-28 06:58
Hi, I will check it, is it on iOS or Android ?

**Comment by Marco97raf** [comment] 2020-05-28 07:17
Sorry, it is on Android

**Comment by FredLuart** [comment] 2020-05-28 14:03
Hi, I was not able to reproduce your issue but I have pushed an update that should fix it.
Can you test it ?

**Comment by Marco97raf** [comment] 2020-05-28 14:36
I tested the last update.
"document.addEventListener is not a function" this problem no longer comes out, but the camera continues to remain busy after hungup.

**Comment by FredLuart** [comment] 2020-05-28 14:39
did you update ReactNativeApiRTC.js ?

        invitation.accept()
            .then((call) => {	            .then((call) => {
                this.setCallListeners(call);	                this.setCallListeners(call);
                **this.currentCall = call;**
            });	            });

**Comment by Marco97raf** [comment] 2020-05-29 12:26
Yes, I use the same logic for my project.

**Comment by FredLuart** [comment] 2020-05-29 12:30
Can you reproduce on our sample ?
I think It is corrected on our sample with the additional : this.currentCall = call;

**Comment by Marco97raf** [comment] 2020-05-29 12:51
I found the problem, passing the stream created with "apiRTC.Stream.createStreamFromUserMedia(null,null, constraints)" the camera is not released. While without passing the stream to "invitation.accept()" the camera is released.
Is there a way to pass constraints to invitation.accept()? I need to lower the frame rate and increase the resolution.
Thank you

**Comment by FredLuart** [comment] 2020-05-29 12:59
It is normal behavior, if you create the stream on application you need to manage the stream.release() : if stream is created with the call, we release it.
You can pass a stream with your needed constraint to accept()

I am closing the issue as it is resolved

**Closed by FredLuart** 2020-05-29 12:59 UTC
